### PR TITLE
feat: implement error handling and exceptions

### PR DESCRIPTION
**Pull request by joseluis-teran-jalafund**
## Trello Ticket

**[Task - 09](https://trello.com/c/AzAhfrYQ/8-task-9-error-hadling-and-validation)**

## Description

This **PR** is on charge of implementing an Exception Handler and Error Logger according to the modules which required besides of only showing friendly messages and do not perform nothing else with that inside of the system.

## Type of Change

Put an `x` in all the boxes that apply:

- [x] ✨ New Feature (non-breaking change which adds functionality)
- [ ] 🛠️ Bug Fix (non-breaking change which fixes an issue)
- [ ] ❌ Breaking Change (fix or feature that would cause existing functionality to change)
- [x] 🧹 Code Refactor
- [ ] ✅ Build Configuration Change
- [x] 📝 Documentation
- [ ] 🗑️ Chore

## Pull Request Checklist

Put an `x` in all the boxes that apply:

- [x] My commit messages are detailed.
- [x] My code follows the code style of this project.
- [ ] No existing features have been broken without good reason.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests pass.

### CODE REVIEW

**Review by ronaldo-mendoza-jalafund — CHANGES_REQUESTED** [review]
Resolves comments

**Comment by joseluis-teran-jalafund** [comment]
> Resolves comments

I need make a rebase to bring the new changes, but my suggestion is to merge first **[PR - 16](https://github.com/programacion-6/Opcion1CanelitaTeam/pull/16)** in order to update the code that this PR have due to **PR - 16** has code refactoring and if I update it now, I'll repeat again the process and correct the code we don't need anymore, which conduces to violate **DRY** principle.

**Review by ronaldo-mendoza-jalafund — CHANGES_REQUESTED** [review]
Resolves the warnings
Possible null reference argument for parameter 'item' in 'bool List<Borrow>.Remove(Borrow item)'.
'BaseException.Message' hides inherited member 'Exception.Message'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword.

**Comment by joseluis-teran-jalafund** [comment]
> Resolves the warnings Possible null reference argument for parameter 'item' in 'bool List.Remove(Borrow item)'. 'BaseException.Message' hides inherited member 'Exception.Message'. To make the current member override that implementation, add the override keyword. Otherwise add the new keyword.

Done. I added those missing handlers.

**Review by ronaldo-mendoza-jalafund — CHANGES_REQUESTED** [review]
imagen_2024-08-25_232229717

resolves missing warnings

**Comment by joseluis-teran-jalafund** [comment]
> imagen_2024-08-25_232229717
> 
> resolves missing warnings

Done.

**Review by ronaldo-mendoza-jalafund — APPROVED** [review]
Nice job

**Pull request merged**
